// catalogo de productos
export const productos = [
  {
    id: 1,
    nombre: "Aparador Uspallata",
    descripcion:
      "Aparador de seis puertas fabricado en nogal sostenible con tiradores metálicos en acabado latón. Su silueta minimalista realza el veteado natural de la madera, creando una pieza que combina funcionalidad y elegancia atemporal para espacios contemporáneos.",
    medidas: "180 × 45 × 75 cm",
    materiales: "Nogal macizo FSC®, herrajes de latón",
    acabado: "Aceite natural ecológico",
    peso: "68kg",
    capacidad: "6 compartimientos interiores",
    precio: 1200,
    img: "https://i.postimg.cc/pXWMvF92/aparador-Uspallata.png",
    categoria: "sala",
    stock: 10,
    caracteristicas: [
      "Construido en nogal macizo certificado FSC®",
      "Tiradores metálicos en acabado latón",
      "Acabado con aceite natural ecológico",
      "6 compartimientos interiores para organización",
      "Fácil mantenimiento: limpiar con paño seco o ligeramente humedecido",
      "Diseño minimalista que realza el veteado natural",
    ],
  },
  {
    id: 2,
    nombre: "Biblioteca Recoleta",
    descripcion:
      "Sistema modular de estantes abierto que combina estructura de acero Sage Green y repisas en roble claro. Perfecta para colecciones y objetos de diseño, su diseño versátil se adapta a cualquier espacio contemporáneo con elegancia funcional.",
    medidas: "100 × 35 × 200 cm",
    materiales: "Estructura de acero, estantes de roble",
    acabado: "Laca mate ecológica",
    capacidad: "45 kg por estante",
    modulares: "5 estantes ajustables",
    precio: 1500,
    img: "https://ibb.co/53c14mr",
    categoria: "sala",
    stock: 7,
    caracteristicas: [
      "Estructura metálica en Sage Green de alta resistencia",
      "Repisas en roble claro de apariencia natural",
      "5 estantes modulables y ajustables",
      "Soporta hasta 45 kg por estante",
      "Acabado en laca mate ecológica resistente",
      "Ideal para libros, objetos de diseño y colecciones",
    ],
  },
  {
    id: 3,
    nombre: "Butaca Mendoza",
    descripcion:
      "Butaca tapizada en bouclé Dusty Rose con base de madera de guatambú. El respaldo curvo abraza el cuerpo y ofrece máximo confort, mientras que su diseño orgánico aporta calidez y sofisticación a cualquier ambiente contemporáneo.",
    medidas: "80 × 75 × 85 cm",
    materiales: "Guatambú macizo, tela bouclé",
    acabado: "Cera vegetal, tapizado premium",
    tapizado: "Repelente al agua y manchas",
    confort: "Espuma alta densidad",
    precio: 1000,
    img: "https://ibb.co/Wv26DMT2",
    categoria: "sala",
    stock: 5,
    caracteristicas: [
      "Tapizado bouclé Dusty Rose, textura lujosa",
      "Base y estructura en guatambú macizo",
      "Respaldo curvo ergonómico que abraza el cuerpo",
      "Relleno con espuma de alta densidad para confort",
      "Tapizado tratado repelente al agua y manchas",
      "Acabado en cera vegetal que realza la madera",
    ],
  },
  {
    id: 4,
    nombre: "Sillón Copacabana",
    descripcion:
      "Sillón lounge en cuero cognac con base giratoria en acero Burnt Sienna. Inspirado en la estética brasilera moderna de los 60, combina comodidad excepcional con un diseño icónico que trasciende tendencias y épocas.",
    medidas: "90 × 85 × 95 cm",
    materiales: "Cuero curtido vegetal, acero pintado",
    acabado: "Cuero anilina premium",
    rotación: "360° silenciosa y suave",
    garantía: "10 años en estructura",
    precio: 1600,
    img: "https://ibb.co/DPPRxNFb",
    categoria: "sala",
    stock: 3,
    caracteristicas: [
      "Tapizado en cuero cognac anilina premium",
      "Base giratoria 360° con mecanismo silencioso",
      "Estructura en acero acabado Burnt Sienna",
      "Diseño inspirado en la estética brasileña de los 60",
      "Garantía extendida de 10 años en estructura",
      "Ideal para lounge, lectura y espacios icónicos",
    ],
  },
  {
    id: 5,
    nombre: "Mesa de Centro Araucaria",
    descripcion:
      "Mesa de centro con sobre circular de mármol Patagonia y base de tres patas en madera de nogal. Su diseño minimalista se convierte en el punto focal perfecto para cualquier sala de estar contemporánea, combinando la frialdad del mármol con la calidez de la madera.",
    medidas: "90 × 90 × 45 cm",
    materiales: "Sobre de mármol Patagonia, patas de nogal",
    acabado: "Mármol pulido, aceite natural en madera",
    peso: "42 kg",
    cargaMáxima: "25 kg distribuidos",
    precio: 400,
    img: "https://ibb.co/s9kjhSZh",
    categoria: "sala",
    stock: 8,
    caracteristicas: [
      "Sobre circular en mármol Patagonia pulido",
      "Base de tres patas en nogal macizo",
      "Combinación de materiales: mármol frío + madera cálida",
      "Acabado en aceite natural para la madera",
      "Soporta hasta 25 kg distribuidos",
      "Diseño minimalista que funciona como punto focal",
    ],
  },
  {
    id: 6,
    nombre: "Mesa de Noche Aconcagua",
    descripcion:
      "Mesa de noche con cajón oculto y repisa inferior en roble certificado FSC®. Su diseño limpio y funcional permite convivir con diferentes estilos de dormitorio, ofreciendo almacenamiento discreto y elegante para objetos personales.",
    medidas: "45 × 35 × 60 cm",
    materiales: "Roble macizo FSC®, herrajes soft-close",
    acabado: "Barniz mate de poliuretano",
    almacenamiento: "1 cajón + repisa inferior",
    características: "Cajón con cierre suave",
    precio: 600,
    img: "https://ibb.co/FbxhryRR",
    categoria: "dormitorio",
    stock: 6,
    caracteristicas: [
      "Construida en roble macizo certificado FSC®",
      "Cajón oculto con mecanismo soft-close",
      "Repisa inferior para almacenaje adicional",
      "Herrajes y guías ocultas de alta calidad",
      "Acabado en barniz mate poliuretano resistente",
      "Diseño compacto y funcional para dormitorios",
    ],
  },
  {
    id: 7,
    nombre: "Cama Neuquén",
    descripcion:
      "Cama plataforma con cabecero flotante tapizado en lino natural y estructura de madera maciza. Su diseño minimalista y sofisticado crea un ambiente de serenidad y elegancia, perfecto para dormitorios contemporáneos que buscan paz y simplicidad.",
    medidas: "160 × 200 × 90 cm",
    materiales: "Roble macizo FSC®, tapizado lino",
    acabado: "Aceite natural, tapizado premium",
    colchón: "Compatible con colchón 160×200",
    características: "Cabecero flotante acolchado",
    precio: 2000,
    img: "https://ibb.co/qMFStkDS",
    categoria: "dormitorio",
    stock: 2,
    caracteristicas: [
      "Estructura y patas en roble macizo FSC®",
      "Cabecero flotante tapizado en lino natural",
      "Compatible con colchón 160×200",
      "Acabado en aceite natural que protege la madera",
      "Tapizado premium con tacto suave",
      "Diseño minimalista que aporta serenidad al dormitorio",
    ],
  },
  {
    id: 8,
    nombre: "Sofá Patagonia",
    descripcion:
      "Sofá de tres cuerpos tapizado en lino Warm Alabaster con patas cónicas de madera. Los cojines combinan espuma de alta resiliencia con plumón reciclado, ofreciendo comodidad duradera y sostenible para el hogar moderno.",
    medidas: "220 × 90 × 80 cm",
    estructura: "Madera de eucalipto certificada FSC®",
    tapizado: "Lino 100% natural premium",
    relleno: "Espuma HR + plumón reciclado",
    sostenibilidad: "Materiales 100% reciclables",
    precio: 1800,
    img: "https://ibb.co/bgmWVDDK",
    categoria: "sala",
    stock: 9,
    caracteristicas: [
      "Tapizado en lino natural premium Warm Alabaster",
      "Estructura en madera de eucalipto certificada FSC®",
      "Cojines con espuma HR y plumón reciclado",
      "Patas cónicas de madera que aportan elegancia",
      "Materiales diseñados para ser reciclables",
      "Diseño para comodidad y uso prolongado",
    ],
  },
  {
    id: 9,
    nombre: "Mesa Comedor Pampa",
    descripcion:
      "Mesa extensible de roble macizo con tablero biselado y sistema de apertura suave. Su diseño robusto y elegante se adapta perfectamente a reuniones íntimas o grandes celebraciones familiares, extendiéndose de 6 a 10 comensales.",
    medidas: "160-240 × 90 × 75 cm",
    materiales: "Roble macizo FSC®, mecanismo alemán",
    acabado: "Aceite-cera natural",
    capacidad: "6-10 comensales",
    extensión: "Sistema de mariposa central",
    precio: 900,
    img: "https://ibb.co/CKCTMfJ2",
    categoria: "comedor",
    stock: 4,
    caracteristicas: [
      "Tablero extensible 160–240 cm con sistema mariposa",
      "Roble macizo certificado FSC® de alta durabilidad",
      "Mecanismo de apertura suave de origen alemán",
      "Acabado en aceite-cera natural que realza la veta",
      "Capacidad para 6 a 10 comensales según extensión",
      "Diseño robusto pensado para uso familiar y eventos",
    ],
  },
  {
    id: 10,
    nombre: "Sillas Córdoba",
    descripcion:
      "Set de cuatro sillas apilables en contrachapado moldeado de nogal y estructura tubular pintada en Sage Green. Su diseño ergonómico y materiales de calidad garantizan comodidad y durabilidad en el uso diario, perfectas para comedores contemporáneos.",
    medidas: "45 × 52 × 80 cm (cada una)",
    materiales: "Contrachapado nogal, tubo de acero",
    acabado: "Laca mate, pintura epoxi",
    apilables: "Hasta 6 sillas",
    incluye: "Set de 4 sillas",
    precio: 300,
    img: "https://ibb.co/vC0mmSY9",
    categoria: "comedor",
    stock: 10,
    caracteristicas: [
      "Asiento y respaldo en contrachapado moldeado de nogal",
      "Estructura tubular de acero pintada en Sage Green",
      "Apilables hasta 6 para fácil almacenaje",
      "Diseño ergonómico para comodidad diaria",
      "Acabado en laca mate y pintura epoxi resistente",
      "Vienen en set de 4, ideales para comedores contemporáneos",
    ],
  },
  {
    id: 11,
    nombre: "Escritorio Costa",
    descripcion:
      "Escritorio compacto con cajón organizado y tapa pasacables integrada en bambú laminado. Ideal para espacios de trabajo en casa, combina funcionalidad moderna con estética minimalista y sostenible, perfecto para el trabajo remoto.",
    medidas: "120 × 60 × 75 cm",
    materiales: "Bambú laminado, herrajes ocultos",
    acabado: "Laca mate resistente",
    almacenamiento: "1 cajón con organizador",
    cables: "Pasacables integrado",
    precio: 1100,
    img: "https://ibb.co/bhBjvtJ",
    categoria: "oficina",
    stock: 6,
    caracteristicas: [
      "Superficie en bambú laminado, sostenible y resistente",
      "Cajón con organizador para accesorios de escritorio",
      "Pasacables integrado para gestión ordenada de cables",
      "Herrajes ocultos que mantienen estética limpia",
      "Acabado en laca mate de alta resistencia",
      "Diseño compacto ideal para home office y espacios reducidos",
    ],
  },
  {
    id: 12,
    nombre: "Silla de Trabajo Belgrano",
    descripcion:
      "Silla ergonómica regulable en altura con respaldo de malla transpirable y asiento tapizado en tejido reciclado. Diseñada para largas jornadas de trabajo con máximo confort y apoyo lumbar, ideal para oficinas en casa y espacios de coworking.",
    medidas: "60 × 60 × 90-100 cm",
    materiales: "Malla técnica, tejido reciclado",
    acabado: "Base cromada, tapizado premium",
    regulación: "Altura + inclinación respaldo",
    certificación: "Ergonomía europea EN 1335",
    precio: 700,
    img: "https://ibb.co/j9D08SV7",
    categoria: "oficina",
    stock: 5,
    caracteristicas: [
      "Respaldo de malla transpirable para ventilación",
      "Asiento tapizado en tejido reciclado de alta resistencia",
      "Regulación de altura y ajuste de inclinación del respaldo",
      "Apoyo lumbar diseñado para largas jornadas",
      "Base cromada robusta y estable",
      "Certificación de ergonomía europea EN 1335",
    ],
  },
];
